// <auto-generated>
//   Produced by Tools/gen-levels.mjs from C:/Users/coryc/alienGame/js/level.js.
//   Do not hand-edit: re-run the generator instead. Lifting the layout straight out of the web
//   build is what guarantees v3's Chicago is the same Chicago, block for block.
// </auto-generated>
using System.Collections.Generic;
using UnityEngine;

namespace UFO {

/// <summary>One entry in the asset catalogue: a model, its real-world height, its collider radius.</summary>
public class Prop {
    public readonly string Key, ResourcePath;
    public readonly float Height;
    /// <summary>Collider radius. -1 means "derive it from the model bounds"; 0 means no collider.</summary>
    public readonly float Radius;
    public readonly float YOffset;
    public Prop(string key, string path, float h, float r, float yOff) {
        Key = key; ResourcePath = path; Height = h; Radius = r; YOffset = yOff;
    }
}

public class Lake { public float X, PierZ0, PierZ1, PierXEnd; }

public class LevelDef {
    public string Name, Subtitle, Weather;
    public int FogColor, Ambient, HemiSky, HemiGround, SunColor, GroundColor;
    public float FogDensity, AmbientIntensity, HemiIntensity, SunIntensity, ArenaRadius;
    public Color SkyTop, SkyHorizon, SkyGlow;
    public Vector3 SunDir;
    public Lake Lake;
    /// <summary>[gridX, gridZ, catalogKey, rotYDegrees, scaleMul?]</summary>
    public object[][] Buildings;
    /// <summary>[x, z, catalogKey, rotYDegrees, scaleMul?]</summary>
    public object[][] Vehicles, Landmarks, Props, Deco;
    /// <summary>[x, z]</summary>
    public object[][] Fires, Beams, Crashes;
    /// <summary>[x, z, rotYDegrees, decalIndex, width, height, color]</summary>
    public object[][] Signs;
}

public static class LevelData {

    /// <summary>A block is a 34 m square with 10 m streets between, so the grid pitch is 44 m.</summary>
    public const float Street = 10f, Block = 34f, Pitch = Street + Block;

    public static readonly Dictionary<string, Prop> Catalog = new Dictionary<string, Prop> {
        ["skyscraper_016"] = new Prop("skyscraper_016", "Models/props/building_skyscraper_016", 46f, -1f, 0f),
        ["skyscraper_020"] = new Prop("skyscraper_020", "Models/props/building_skyscraper_020", 52f, -1f, 0f),
        ["skyscraper_030"] = new Prop("skyscraper_030", "Models/props/building_skyscraper_030", 40f, -1f, 0f),
        ["skyscraper_044"] = new Prop("skyscraper_044", "Models/props/building_skyscraper_044", 34f, -1f, 0f),
        ["skyscraper_046"] = new Prop("skyscraper_046", "Models/props/building_skyscraper_046", 58f, -1f, 0f),
        ["skyscraper_048"] = new Prop("skyscraper_048", "Models/props/building_skyscraper_048", 44f, -1f, 0f),
        ["residential_010"] = new Prop("residential_010", "Models/props/building_residential_010", 9f, -1f, 0f),
        ["residential_013"] = new Prop("residential_013", "Models/props/building_residential_013", 11f, -1f, 0f),
        ["residential_015"] = new Prop("residential_015", "Models/props/building_residential_015", 10f, -1f, 0f),
        ["residential_018"] = new Prop("residential_018", "Models/props/building_residential_018", 22f, -1f, 0f),
        ["residential_022"] = new Prop("residential_022", "Models/props/building_residential_022", 16f, -1f, 0f),
        ["commercial_006"] = new Prop("commercial_006", "Models/props/building_commercial_006", 8f, -1f, 0f),
        ["industrial_019"] = new Prop("industrial_019", "Models/props/building_industrial_019", 9f, -1f, 0f),
        ["industrial_020"] = new Prop("industrial_020", "Models/props/building_industrial_020", 18f, -1f, 0f),
        ["car_001"] = new Prop("car_001", "Models/props/vehicle_civilian_001", 1.4f, 1.6f, 0f),
        ["car_003"] = new Prop("car_003", "Models/props/vehicle_civilian_003", 1.9f, 1.7f, 0f),
        ["van_009"] = new Prop("van_009", "Models/props/vehicle_civilian_009", 2.3f, 1.9f, 0f),
        ["truck_012"] = new Prop("truck_012", "Models/props/vehicle_civilian_012", 3f, -1f, 0f),
        ["excavator_013"] = new Prop("excavator_013", "Models/props/vehicle_civilian_013", 3.2f, -1f, 0f),
        ["limo_014"] = new Prop("limo_014", "Models/props/vehicle_civilian_014", 1.5f, 2.2f, 0f),
        ["mixer_019"] = new Prop("mixer_019", "Models/props/vehicle_civilian_019", 3.6f, -1f, 0f),
        ["hover_021"] = new Prop("hover_021", "Models/props/vehicle_civilian_021", 1.6f, 1.6f, 0f),
        ["dropship"] = new Prop("dropship", "Models/props/vehicle_alien_003", 9f, -1f, 0f),
        ["tripod"] = new Prop("tripod", "Models/props/vehicle_alien_019", 14f, -1f, 0f),
        ["hospital"] = new Prop("hospital", "Models/props/building_hospital", 24f, -1f, 0f),
        ["office_mid"] = new Prop("office_mid", "Models/props/building_office_mid", 28f, -1f, 0f),
        ["police_station"] = new Prop("police_station", "Models/props/building_police_station", 12f, -1f, 0f),
        ["fire_station"] = new Prop("fire_station", "Models/props/building_fire_station", 10f, -1f, 0f),
        ["barrier_jersey"] = new Prop("barrier_jersey", "Models/props/barrier_jersey", 0.9f, 1.1f, 0f),
        ["sandbags"] = new Prop("sandbags", "Models/props/sandbags", 1f, 1.1f, 0f),
        ["hydrant"] = new Prop("hydrant", "Models/props/hydrant", 0.8f, 0.3f, 0f),
        ["traffic_light"] = new Prop("traffic_light", "Models/props/traffic_light", 5.5f, 0.35f, 0f),
        ["dumpster"] = new Prop("dumpster", "Models/props/dumpster", 1.5f, 1.2f, 0f),
        ["car_wreck"] = new Prop("car_wreck", "Models/props/car_wreck", 1.3f, 2f, 0f),
        ["rubble"] = new Prop("rubble", "Models/props/rubble", 1.2f, 1.6f, 0f),
        ["drop_pod"] = new Prop("drop_pod", "Models/props/drop_pod", 3.2f, 1.6f, 0f),
        ["bus_shelter"] = new Prop("bus_shelter", "Models/props/bus_shelter", 2.8f, 2f, 0f),
        ["l_track"] = new Prop("l_track", "Models/props/l_track", 7.5f, 0f, 0f),
        ["ferris_wheel"] = new Prop("ferris_wheel", "Models/props/ferris_wheel", 45f, 6f, 0f),
        ["tree"] = new Prop("tree", "Models/props/tree", 9f, 0.45f, 0f),
        ["planter"] = new Prop("planter", "Models/props/planter", 1f, 0.7f, 0f),
        ["bench"] = new Prop("bench", "Models/props/bench", 0.9f, 0.6f, 0f),
        ["trash_can"] = new Prop("trash_can", "Models/props/trash_can", 1.1f, 0.4f, 0f),
        ["mailbox"] = new Prop("mailbox", "Models/props/mailbox", 1.3f, 0.4f, 0f),
        ["news_box"] = new Prop("news_box", "Models/props/news_box", 1.2f, 0.4f, 0f),
        ["cta_bus"] = new Prop("cta_bus", "Models/props/cta_bus", 3.3f, 0f, 0f),
        ["taxi"] = new Prop("taxi", "Models/props/taxi", 1.5f, 1.7f, 0f),
        ["police_car"] = new Prop("police_car", "Models/props/police_car", 1.5f, 1.8f, 0f),
        ["container"] = new Prop("container", "Models/props/container", 2.6f, 0f, 0f),
        ["pallets"] = new Prop("pallets", "Models/props/pallets", 1.2f, 0.9f, 0f),
        ["hotdog_cart"] = new Prop("hotdog_cart", "Models/props/hotdog_cart", 1.8f, 1f, 0f),
        ["cones"] = new Prop("cones", "Models/props/cones", 0.75f, 0f, 0f),
        ["mothership"] = new Prop("mothership", "Models/props/mothership", 110f, 0f, 0f),
        ["yacht"] = new Prop("yacht", "Models/props/yacht", 6f, 0f, -1.6f),
        ["pier_kiosk"] = new Prop("pier_kiosk", "Models/props/pier_kiosk", 3.5f, 2.2f, 0f),
    };

    public static Prop Find(string key) => Catalog.TryGetValue(key, out var p) ? p : null;

    public static readonly LevelDef[] Levels = {
        new LevelDef {
            Name = "THE LOOP", Subtitle = "Downtown Chicago — first contact",
            FogColor = 0x0a0c1e, FogDensity = 0.0048f,
            SkyTop = new Color(0.02f, 0.02f, 0.09f),
            SkyHorizon = new Color(0.16f, 0.07f, 0.1f),
            SkyGlow = new Color(0.35f, 0.12f, 0.05f),
            Ambient = 0x3a4a70, AmbientIntensity = 0.9f,
            HemiSky = 0x6a80c0, HemiGround = 0x2a2030, HemiIntensity = 1.1f,
            SunColor = 0x9fb4ff, SunIntensity = 1.6f,
            SunDir = new Vector3(30f, 60f, 20f),
            GroundColor = 0x2a2a2e, ArenaRadius = 92f,
            Weather = "clear",
            Lake = null,
            Buildings = new object[][] {
            new object[] { -2f, -2f, "skyscraper_046", 0f },
            new object[] { -1f, -2f, "skyscraper_020", 90f },
            new object[] { 0f, -2f, "residential_018", 0f },
            new object[] { 1f, -2f, "hospital", 0f },
            new object[] { 2f, -2f, "skyscraper_030", 180f },
            new object[] { -2f, -1f, "residential_022", 90f },
            new object[] { 2f, -1f, "skyscraper_044", 0f },
            new object[] { -2f, 0f, "police_station", 0f },
            new object[] { 2f, 0f, "industrial_020", 270f },
            new object[] { -2f, 1f, "residential_015", 0f },
            new object[] { 2f, 1f, "residential_013", 180f },
            new object[] { -2f, 2f, "skyscraper_048", 0f },
            new object[] { -1f, 2f, "residential_010", 0f },
            new object[] { 0f, 2f, "industrial_019", 0f },
            new object[] { 1f, 2f, "skyscraper_020", 270f },
            new object[] { 2f, 2f, "skyscraper_016", 180f },
            new object[] { -1f, -1f, "residential_013", 0f },
            new object[] { 1f, -1f, "commercial_006", 90f },
            new object[] { -1f, 1f, "residential_010", 180f },
            new object[] { 1f, 1f, "residential_022", 270f },
            },
            Vehicles = new object[][] {
            new object[] { -6f, -30f, "car_001", 80f },
            new object[] { 8f, -18f, "van_009", 10f },
            new object[] { 4f, 12f, "car_003", 200f },
            new object[] { -14f, 6f, "truck_012", 95f },
            new object[] { 18f, 26f, "limo_014", 5f },
            new object[] { -30f, -8f, "car_003", 0f },
            new object[] { 30f, 10f, "mixer_019", 180f },
            new object[] { -22f, 30f, "hover_021", 40f },
            new object[] { 26f, -32f, "car_001", 270f },
            new object[] { 0f, 44f, "excavator_013", 90f },
            new object[] { -44f, 0f, "van_009", 0f, 80f },
            new object[] { 44f, -2f, "car_001", 175f },
            new object[] { 12f, -44f, "truck_012", 100f, -90f },
            new object[] { -10f, 40f, "car_003", 20f },
            },
            Landmarks = new object[][] {
            new object[] { 46f, 46f, "dropship", 30f },
            new object[] { -48f, -46f, "tripod", 0f },
            },
            Props = new object[][] {
            new object[] { -9f, -9f, "barrier_jersey", 45f },
            new object[] { 9f, -9f, "barrier_jersey", -45f },
            new object[] { -11f, 6f, "barrier_jersey", 90f },
            new object[] { 11f, 6f, "barrier_jersey", 90f },
            new object[] { 0f, -14f, "sandbags", 0f },
            new object[] { -16f, 0f, "sandbags", 90f },
            new object[] { 16f, 2f, "sandbags", 90f },
            new object[] { 4f, 15f, "sandbags", 0f },
            new object[] { 66f, 40f, "drop_pod", 20f },
            new object[] { -40f, -66f, "drop_pod", 160f },
            new object[] { -66f, 60f, "drop_pod", 300f },
            new object[] { -27f, 40f, "bus_shelter", 90f },
            new object[] { 27f, -40f, "bus_shelter", 270f },
            new object[] { -62.5f, -110f, "l_track", 0f },
            new object[] { -50f, -110f, "l_track", 0f },
            new object[] { -37.5f, -110f, "l_track", 0f },
            new object[] { -25f, -110f, "l_track", 0f },
            new object[] { -12.5f, -110f, "l_track", 0f },
            new object[] { 0f, -110f, "l_track", 0f },
            new object[] { 12.5f, -110f, "l_track", 0f },
            new object[] { 25f, -110f, "l_track", 0f },
            new object[] { 37.5f, -110f, "l_track", 0f },
            new object[] { 50f, -110f, "l_track", 0f },
            new object[] { 62.5f, -110f, "l_track", 0f },
            },
            Deco = new object[][] {

            },
            Fires = new object[][] {
            new object[] { -6f, -30f },
            new object[] { 30f, 10f },
            new object[] { 12f, -44f },
            new object[] { 46f, 46f },
            new object[] { -44f, 0f },
            },
            Beams = new object[][] {
            new object[] { -150f, -170f },
            new object[] { 190f, 60f },
            },
            Crashes = new object[][] {
            new object[] { -22f, -22f },
            new object[] { 22f, 66f },
            },
            Signs = new object[][] {
            new object[] { -44f, -26.5f, 0f, 0f, 9f, 9f, 16724096f },
            new object[] { 26.5f, -44f, 90f, 1f, 8f, 8f, 3195135f },
            new object[] { 44f, 26.5f, 180f, 2f, 9f, 9f, 16756768f },
            new object[] { -26.5f, 44f, 270f, 3f, 8f, 8f, 4259728f },
            new object[] { -26.5f, -44f, 90f, 2f, 12f, 7f, 16724096f },
            new object[] { 44f, -26.5f, 0f, 3f, 11f, 7f, 3195135f },
            },
        },
        new LevelDef {
            Name = "RIVER NORTH", Subtitle = "Warehouse district — the counter-attack",
            FogColor = 0x0c1410, FogDensity = 0.0055f,
            SkyTop = new Color(0.02f, 0.04f, 0.05f),
            SkyHorizon = new Color(0.1f, 0.12f, 0.08f),
            SkyGlow = new Color(0.3f, 0.2f, 0.05f),
            Ambient = 0x405a50, AmbientIntensity = 0.85f,
            HemiSky = 0x7aa090, HemiGround = 0x24281a, HemiIntensity = 1.1f,
            SunColor = 0xc8d8b0, SunIntensity = 1.5f,
            SunDir = new Vector3(-30f, 50f, -20f),
            GroundColor = 0x26282a, ArenaRadius = 92f,
            Weather = "rain",
            Lake = null,
            Buildings = new object[][] {
            new object[] { -2f, -2f, "industrial_020", 0f },
            new object[] { -1f, -2f, "fire_station", 90f },
            new object[] { 0f, -2f, "residential_010", 0f },
            new object[] { 1f, -2f, "industrial_020", 180f },
            new object[] { 2f, -2f, "residential_022", 0f },
            new object[] { -2f, -1f, "residential_013", 0f },
            new object[] { 2f, -1f, "industrial_019", 270f },
            new object[] { -2f, 0f, "industrial_019", 90f },
            new object[] { -2f, 1f, "residential_015", 0f },
            new object[] { 2f, 1f, "industrial_020", 90f },
            new object[] { -2f, 2f, "skyscraper_044", 0f },
            new object[] { -1f, 2f, "residential_018", 0f },
            new object[] { 0f, 2f, "industrial_019", 180f },
            new object[] { 1f, 2f, "residential_015", 0f },
            new object[] { 2f, 2f, "skyscraper_030", 0f },
            new object[] { -1f, 0f, "office_mid", 0f },
            new object[] { 1f, 0f, "residential_010", 90f },
            },
            Vehicles = new object[][] {
            new object[] { -8f, -24f, "truck_012", 90f },
            new object[] { 10f, -20f, "mixer_019", 0f },
            new object[] { 6f, 16f, "excavator_013", 200f },
            new object[] { -16f, 8f, "van_009", 95f },
            new object[] { 22f, 30f, "truck_012", 5f },
            new object[] { -32f, -10f, "car_001", 0f, 75f },
            new object[] { 32f, 12f, "car_003", 180f },
            new object[] { -24f, 32f, "van_009", 40f },
            new object[] { 28f, -30f, "limo_014", 270f },
            new object[] { 0f, -44f, "hover_021", 90f },
            },
            Landmarks = new object[][] {
            new object[] { -46f, 44f, "dropship", 120f },
            new object[] { 48f, -44f, "tripod", 60f },
            },
            Props = new object[][] {
            new object[] { -10f, -8f, "barrier_jersey", 30f },
            new object[] { 10f, -8f, "barrier_jersey", -30f },
            new object[] { -12f, 8f, "barrier_jersey", 100f },
            new object[] { 12f, 8f, "barrier_jersey", 80f },
            new object[] { 0f, -16f, "sandbags", 0f },
            new object[] { -17f, 3f, "sandbags", 90f },
            new object[] { 17f, -1f, "sandbags", 90f },
            new object[] { 2f, 16f, "sandbags", 0f },
            new object[] { 66f, 40f, "drop_pod", 20f },
            new object[] { -40f, -66f, "drop_pod", 160f },
            new object[] { -66f, 60f, "drop_pod", 300f },
            new object[] { 40f, 66f, "drop_pod", 80f },
            new object[] { -27f, 40f, "bus_shelter", 90f },
            new object[] { 78f, -10f, "container", 90f },
            new object[] { 84f, -10f, "container", 90f },
            new object[] { 90f, -10f, "container", 90f },
            new object[] { 78f, -3f, "container", 90f },
            new object[] { 84f, -3f, "container", 90f },
            new object[] { 90f, -3f, "container", 90f },
            new object[] { 78f, 4f, "container", 90f },
            new object[] { 84f, 4f, "container", 90f },
            new object[] { 78f, -10f, "container", 90f, 2.6f },
            new object[] { 84f, -3f, "container", 90f, 2.6f },
            new object[] { 78f, 11f, "container", 90f },
            new object[] { 90f, 11f, "container", 90f },
            new object[] { 84f, 10f, "pallets", 0f },
            new object[] { 90f, 4f, "pallets", 90f },
            new object[] { 81f, 8f, "pallets", 30f },
            new object[] { -110f, -62.5f, "l_track", 90f },
            new object[] { -110f, -50f, "l_track", 90f },
            new object[] { -110f, -37.5f, "l_track", 90f },
            new object[] { -110f, -25f, "l_track", 90f },
            new object[] { -110f, -12.5f, "l_track", 90f },
            new object[] { -110f, 0f, "l_track", 90f },
            new object[] { -110f, 12.5f, "l_track", 90f },
            new object[] { -110f, 25f, "l_track", 90f },
            new object[] { -110f, 37.5f, "l_track", 90f },
            new object[] { -110f, 50f, "l_track", 90f },
            new object[] { -110f, 62.5f, "l_track", 90f },
            },
            Deco = new object[][] {

            },
            Fires = new object[][] {
            new object[] { -8f, -24f },
            new object[] { 10f, -20f },
            new object[] { 32f, 12f },
            new object[] { -32f, -10f },
            },
            Beams = new object[][] {
            new object[] { 160f, -150f },
            new object[] { -180f, 40f },
            },
            Crashes = new object[][] {
            new object[] { -22f, 22f },
            new object[] { 66f, -22f },
            },
            Signs = new object[][] {
            new object[] { -44f, -26.5f, 0f, 1f, 7f, 8f, 3195135f },
            new object[] { 26.5f, 44f, 270f, 3f, 8f, 8f, 16756768f },
            new object[] { 44f, 26.5f, 180f, 0f, 9f, 9f, 16724096f },
            new object[] { -26.5f, 0f, 90f, 2f, 6f, 7f, 4259728f },
            },
        },
        new LevelDef {
            Name = "LAKEFRONT", Subtitle = "Navy Pier — hold the shoreline",
            FogColor = 0x0a1020, FogDensity = 0.004f,
            SkyTop = new Color(0.01f, 0.02f, 0.08f),
            SkyHorizon = new Color(0.1f, 0.1f, 0.18f),
            SkyGlow = new Color(0.3f, 0.16f, 0.08f),
            Ambient = 0x3a4a80, AmbientIntensity = 0.9f,
            HemiSky = 0x5a80d0, HemiGround = 0x202838, HemiIntensity = 1.1f,
            SunColor = 0xb0c4ff, SunIntensity = 1.5f,
            SunDir = new Vector3(-40f, 55f, 30f),
            GroundColor = 0x2a2a2e, ArenaRadius = 92f,
            Weather = "clear",
            Lake = new Lake { X = 22f, PierZ0 = -7f, PierZ1 = 7f, PierXEnd = 80f },
            Buildings = new object[][] {
            new object[] { -2f, -2f, "skyscraper_046", 0f },
            new object[] { -1f, -2f, "skyscraper_020", 90f },
            new object[] { 0f, -2f, "residential_018", 0f },
            new object[] { -2f, -1f, "hospital", 90f },
            new object[] { 0f, -1f, "commercial_006", 0f },
            new object[] { -2f, 0f, "skyscraper_044", 0f },
            new object[] { -1f, 0f, "residential_013", 90f },
            new object[] { -2f, 1f, "residential_015", 0f },
            new object[] { 0f, 1f, "industrial_019", 180f },
            new object[] { -2f, 2f, "skyscraper_048", 0f },
            new object[] { -1f, 2f, "residential_010", 0f },
            new object[] { 0f, 2f, "commercial_006", 90f },
            new object[] { -1f, -1f, "residential_013", 0f },
            new object[] { -1f, 1f, "residential_022", 270f },
            },
            Vehicles = new object[][] {
            new object[] { -6f, -30f, "van_009", 80f },
            new object[] { 8f, -18f, "car_003", 10f, 70f },
            new object[] { -14f, 6f, "truck_012", 95f },
            new object[] { 4f, 30f, "limo_014", 5f },
            new object[] { -30f, -8f, "car_001", 0f },
            new object[] { -22f, 30f, "hover_021", 40f },
            new object[] { -44f, 0f, "mixer_019", 0f },
            new object[] { -10f, 40f, "car_003", 20f },
            new object[] { 12f, -46f, "car_001", 100f },
            },
            Landmarks = new object[][] {
            new object[] { -48f, 46f, "dropship", 30f },
            new object[] { -48f, -46f, "tripod", 0f },
            },
            Props = new object[][] {
            new object[] { -9f, -9f, "barrier_jersey", 45f },
            new object[] { 9f, -9f, "barrier_jersey", -45f },
            new object[] { -11f, 6f, "barrier_jersey", 90f },
            new object[] { 11f, 6f, "barrier_jersey", 90f },
            new object[] { 0f, -14f, "sandbags", 0f },
            new object[] { -16f, 0f, "sandbags", 90f },
            new object[] { 16f, 2f, "sandbags", 90f },
            new object[] { -40f, -66f, "drop_pod", 160f },
            new object[] { -66f, 60f, "drop_pod", 300f },
            new object[] { 16f, -62f, "drop_pod", 40f },
            new object[] { -27f, 40f, "bus_shelter", 90f },
            new object[] { 76f, 0f, "ferris_wheel", 90f },
            new object[] { -110f, -64f, "l_track", 90f },
            new object[] { -110f, -50f, "l_track", 90f },
            new object[] { -110f, -36f, "l_track", 90f },
            new object[] { -110f, -22f, "l_track", 90f },
            new object[] { -110f, -8f, "l_track", 90f },
            new object[] { -110f, 6f, "l_track", 90f },
            new object[] { -110f, 20f, "l_track", 90f },
            new object[] { -110f, 34f, "l_track", 90f },
            new object[] { -110f, 48f, "l_track", 90f },
            new object[] { -110f, 62f, "l_track", 90f },
            },
            Deco = new object[][] {
            new object[] { 30f, -6.4f, "barrier_jersey", 0f },
            new object[] { 38f, -6.4f, "barrier_jersey", 0f },
            new object[] { 46f, -6.4f, "barrier_jersey", 0f },
            new object[] { 54f, -6.4f, "barrier_jersey", 0f },
            new object[] { 30f, 6.4f, "barrier_jersey", 0f },
            new object[] { 38f, 6.4f, "barrier_jersey", 0f },
            new object[] { 46f, 6.4f, "barrier_jersey", 0f },
            new object[] { 54f, 6.4f, "barrier_jersey", 0f },
            new object[] { 34f, 4.5f, "pier_kiosk", 0f },
            new object[] { 58f, -4.5f, "pier_kiosk", 180f },
            new object[] { 66f, 4f, "sandbags", 0f },
            new object[] { 44f, -4f, "sandbags", 90f },
            new object[] { 40f, -16f, "yacht", 10f },
            new object[] { 56f, 16f, "yacht", 190f },
            new object[] { 30f, 24f, "yacht", 160f },
            },
            Fires = new object[][] {
            new object[] { 8f, -18f },
            new object[] { -44f, 0f },
            new object[] { 4f, 30f },
            },
            Beams = new object[][] {
            new object[] { -160f, -150f },
            new object[] { -190f, 60f },
            },
            Crashes = new object[][] {
            new object[] { -22f, -22f },
            new object[] { -66f, 22f },
            },
            Signs = new object[][] {
            new object[] { -44f, -26.5f, 0f, 1f, 9f, 9f, 3195135f },
            new object[] { -26.5f, 44f, 270f, 3f, 8f, 8f, 4259728f },
            new object[] { -44f, 26.5f, 180f, 0f, 9f, 9f, 16724096f },
            new object[] { -26.5f, -44f, 90f, 2f, 12f, 7f, 16756768f },
            },
        },
    };
}

}
