// gen-levels.mjs - lift CATALOG and LEVELS out of v2's js/level.js and emit them as C#.
// The arrays are pure data literals, so they eval cleanly with no three.js in scope. Generating
// rather than transcribing means the Unity layout is provably the same layout as the web build.
import fs from 'node:fs';

const SRC = 'C:/Users/coryc/alienGame/js/level.js';
const OUT = 'C:/Users/coryc/ufoUnityShooter/Assets/Scripts/Level/LevelData.cs';
const src = fs.readFileSync(SRC, 'utf8');

function sliceLiteral(text, startMarker, open, close) {
  const i = text.indexOf(startMarker);
  if (i < 0) throw new Error('marker not found: ' + startMarker);
  const s = text.indexOf(open, i);
  let depth = 0, inStr = null, j = s;
  for (; j < text.length; j++) {
    const c = text[j], p = text[j - 1];
    if (inStr) { if (c === inStr && p !== String.fromCharCode(92)) inStr = null; continue; }
    if (c === "'" || c === '"' || c === '`') { inStr = c; continue; }
    if (c === '/' && text[j + 1] === '/') { j = text.indexOf('\n', j); continue; }
    if (c === open) depth++;
    else if (c === close) { depth--; if (depth === 0) return text.slice(s, j + 1); }
  }
  throw new Error('unterminated literal');
}

const catalogSrc = sliceLiteral(src, 'const CATALOG', '{', '}');
const levelsSrc  = sliceLiteral(src, 'export const LEVELS', '[', ']');

const CATALOG = eval('(' + catalogSrc + ')');
const LEVELS  = eval('(' + levelsSrc + ')');

const f = (n) => (typeof n === 'number' ? (Number.isInteger(n) ? n + 'f' : n + 'f') : '0f');
const s = (v) => (v == null ? 'null' : JSON.stringify(v));
const hex = (n) => '0x' + (n >>> 0).toString(16).padStart(6, '0');

// --- catalogue -------------------------------------------------------------
const catLines = Object.entries(CATALOG).map(([k, v]) => {
  const res = 'Models/props/' + v.file.split('/').pop().replace(/\.glb$/, '');
  return `        ["${k}"] = new Prop("${k}", "${res}", ${f(v.h)}, ${f(v.r != null ? v.r : -1)}, ${v.yOff ? f(v.yOff) : '0f'}),`;
}).join('\n');

// --- levels ----------------------------------------------------------------
function arr2(list, n) {
  // rows of mixed number/string; emit as new object[]{...}
  return (list || []).map((row) => '            new object[] { ' + row.map((c) =>
    typeof c === 'string' ? `"${c}"` : (typeof c === 'number' ? f(c) : 'null')).join(', ') + ' },').join('\n');
}

const levelLines = LEVELS.map((L) => {
  const sky = L.sky;
  const lake = L.lake
    ? `new Lake { X = ${f(L.lake.x)}, PierZ0 = ${f(L.lake.pier.z0)}, PierZ1 = ${f(L.lake.pier.z1)}, PierXEnd = ${f(L.lake.pier.xEnd)} }`
    : 'null';
  return `        new LevelDef {
            Name = ${s(L.name)}, Subtitle = ${s(L.subtitle)},
            FogColor = ${hex(L.fog.color)}, FogDensity = ${f(L.fog.density)},
            SkyTop = new Color(${sky.top.map(f).join(', ')}),
            SkyHorizon = new Color(${sky.horizon.map(f).join(', ')}),
            SkyGlow = new Color(${sky.glow.map(f).join(', ')}),
            Ambient = ${hex(L.ambient)}, AmbientIntensity = ${f(L.ambientI)},
            HemiSky = ${hex(L.hemi[0])}, HemiGround = ${hex(L.hemi[1])}, HemiIntensity = ${f(L.hemi[2])},
            SunColor = ${hex(L.sun.color)}, SunIntensity = ${f(L.sun.intensity)},
            SunDir = new Vector3(${L.sun.pos.map(f).join(', ')}),
            GroundColor = ${hex(L.ground)}, ArenaRadius = ${f(L.arenaRadius)},
            Weather = ${s(L.weather || 'clear')},
            Lake = ${lake},
            Buildings = new object[][] {
${arr2(L.buildings)}
            },
            Vehicles = new object[][] {
${arr2(L.vehicles)}
            },
            Landmarks = new object[][] {
${arr2(L.landmarks)}
            },
            Props = new object[][] {
${arr2(L.props)}
            },
            Deco = new object[][] {
${arr2(L.deco)}
            },
            Fires = new object[][] {
${arr2(L.fires)}
            },
            Beams = new object[][] {
${arr2(L.beams)}
            },
            Crashes = new object[][] {
${arr2(L.crashes)}
            },
            Signs = new object[][] {
${arr2(L.signs)}
            },
        },`;
}).join('\n');

const cs = `// <auto-generated>
//   Produced by Tools/gen-levels.mjs from C:/Users/coryc/alienGame/js/level.js.
//   Do not hand-edit: re-run the generator instead. Lifting the layout straight out of the web
//   build is what guarantees v3's Chicago is the same Chicago, block for block.
// </auto-generated>
using System.Collections.Generic;
using UnityEngine;

namespace UFO {

/// <summary>One entry in the asset catalogue: a model, its real-world height, its collider radius.</summary>
public class Prop {
    public readonly string Key, ResourcePath;
    public readonly float Height;
    /// <summary>Collider radius. -1 means "derive it from the model bounds"; 0 means no collider.</summary>
    public readonly float Radius;
    public readonly float YOffset;
    public Prop(string key, string path, float h, float r, float yOff) {
        Key = key; ResourcePath = path; Height = h; Radius = r; YOffset = yOff;
    }
}

public class Lake { public float X, PierZ0, PierZ1, PierXEnd; }

public class LevelDef {
    public string Name, Subtitle, Weather;
    public int FogColor, Ambient, HemiSky, HemiGround, SunColor, GroundColor;
    public float FogDensity, AmbientIntensity, HemiIntensity, SunIntensity, ArenaRadius;
    public Color SkyTop, SkyHorizon, SkyGlow;
    public Vector3 SunDir;
    public Lake Lake;
    /// <summary>[gridX, gridZ, catalogKey, rotYDegrees, scaleMul?]</summary>
    public object[][] Buildings;
    /// <summary>[x, z, catalogKey, rotYDegrees, scaleMul?]</summary>
    public object[][] Vehicles, Landmarks, Props, Deco;
    /// <summary>[x, z]</summary>
    public object[][] Fires, Beams, Crashes;
    /// <summary>[x, z, rotYDegrees, decalIndex, width, height, color]</summary>
    public object[][] Signs;
}

public static class LevelData {

    /// <summary>A block is a 34 m square with 10 m streets between, so the grid pitch is 44 m.</summary>
    public const float Street = 10f, Block = 34f, Pitch = Street + Block;

    public static readonly Dictionary<string, Prop> Catalog = new Dictionary<string, Prop> {
${catLines}
    };

    public static Prop Find(string key) => Catalog.TryGetValue(key, out var p) ? p : null;

    public static readonly LevelDef[] Levels = {
${levelLines}
    };
}

}
`;

fs.mkdirSync('C:/Users/coryc/ufoUnityShooter/Assets/Scripts/Level', { recursive: true });
fs.writeFileSync(OUT, cs);
console.log('wrote', OUT);
console.log('catalog entries:', Object.keys(CATALOG).length, '| levels:', LEVELS.length);
for (const L of LEVELS) {
  console.log(`  ${L.name}: buildings=${(L.buildings||[]).length} vehicles=${(L.vehicles||[]).length} props=${(L.props||[]).length} deco=${(L.deco||[]).length} signs=${(L.signs||[]).length}`);
}
